spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect    
    
# local 환경
---
spring:
  profiles: local
  datasource:
#        url: jdbc:mariadb://localhost:3307/webservice
#        username: root
#        password: eodfks09
#        driver-class-name: org.mariadb.jdbc.Driver
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true  
      
# 운영 환경
---
spring:
  profiles: set1
  profiles.include: real-db
  
#  datasource:
#    url: jdbc:mariadb://springbootwebservice.cbg3mvbtqwas.ap-northeast-2.rds.amazonaws.com:3306/webservice
#    username: youngran
#    password: eodfks09
#    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8081

---
spring:
  profiles: set2
  profiles.include: real-db
  
#  datasource:
#    url: jdbc:mariadb://springbootwebservice.cbg3mvbtqwas.ap-northeast-2.rds.amazonaws.com:3306/webservice
#    username: youngran
#    password: eodfks09
#    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8082
  
  
  